/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        "./app/**/*.{js,jsx,ts,tsx}",
        "./components/**/*.{js,jsx,ts,tsx}",
        "./lib/**/*.{js,jsx,ts,tsx}",
    ],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            fontSize: {
                xxs: "0.625rem",
            },
            keyframes: {
                "fade-in": {
                    "0%": { opacity: "0", transform: "translateY(10px)" },
                    "100%": { opacity: "1", transform: "translateY(0)" },
                },
            },
            animation: {
                "fade-in": "fade-in 0.5s ease-out",
            },
            screens: {
                '3xl': '1920px',
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
            },
            colors: {
                green1: "#b49a67",
                green2: "#b49a6719",
                green3: "#b49a6714",
                greendeep: "#9A8257",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                bsecondary: {
                    100: "#C2A57E",
                    300: "#B8957A",
                    400: "#F7F4EF",
                    500: "#b49a67",
                    600: "#806A47",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                primary: {
                    DEFAULT: "#b49a67",
                    foreground: "hsl(var(--primary-foreground))",
                    50: "#F7F4EF",
                    100: "#EFE7DB",
                    200: "#E0D1BC",
                    300: "#D1BB9D",
                    400: "#C2A57E",
                    500: "#b49a67",
                    600: "#9A8257",
                    700: "#806A47",
                    800: "#665237",
                    900: "#4C3A27",
                    1000: "#332518",
                },
                "primary-dark": "#9A8257",
                "primary-light": "#E0D1BC",
                secondary: {
                    DEFAULT: "#0D0A0B",
                    foreground: "#ffffff",
                    50: "#F5F4F5",
                    100: "#E8E6E8",
                    200: "#D4D1D4",
                    300: "#B8B4B8",
                    400: "#9A969A",
                    500: "#0D0A0B",
                    600: "#0B0809",
                    700: "#090607",
                    800: "#070405",
                    900: "#050203",
                    1000: "#030101",
                },
                tertiary: {
                    DEFAULT: "#5F0F40",
                    foreground: "#ffffff",
                    50: "#F5E8EF",
                    100: "#E8D1DB",
                    200: "#D4B8C8",
                    300: "#B895A8",
                    400: "#9A6F8A",
                    500: "#5F0F40",
                    600: "#4F0C36",
                    700: "#3F092C",
                    800: "#2F0622",
                    900: "#1F0418",
                    1000: "#0F020E",
                },
                shade: {
                    300: "#707070",
                    200: "#F7F4EF",
                    100: "#F7F4EF",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                chart: {
                    "1": "hsl(var(--chart-1))",
                    "2": "hsl(var(--chart-2))",
                    "3": "hsl(var(--chart-3))",
                    "4": "hsl(var(--chart-4))",
                    "5": "hsl(var(--chart-5))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            boxShadow: {
                low: "var(--shadow-elevation-low)",
                medium: "var(--shadow-elevation-medium)",
                high: "var(--shadow-elevation-high)",
            },
            fontFamily: {
                sans: ["Poppins_400Regular", "system-ui"],
                medium: ["Poppins_500Medium", "system-ui"],
                semibold: ["Poppins_600SemiBold", "system-ui"],
                bold: ["Poppins_700Bold", "system-ui"],
            },
        },
    },
    plugins: [],
};